version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: criadordigital_redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - screenshot_network
    restart: unless-stopped

  api:
    build: .
    container_name: screenshot_api
    command: ./start.sh api
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_USER=default
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - CACHE_DIR=/tmp/screenshot_cache
      - PLAYWRIGHT_BROWSERS_PATH=/ms-playwright
    volumes:
      - ./screenshot_cache:/tmp/screenshot_cache
      - playwright_browsers:/ms-playwright
    depends_on:
      - redis
    networks:
      - screenshot_network
    restart: unless-stopped

  worker:
    build: .
    container_name: screenshot_worker
    command: ./start.sh worker
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_USER=default
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - CACHE_DIR=/tmp/screenshot_cache
      - PLAYWRIGHT_BROWSERS_PATH=/ms-playwright
    volumes:
      - ./screenshot_cache:/tmp/screenshot_cache
      - playwright_browsers:/ms-playwright
    depends_on:
      - redis
    networks:
      - screenshot_network
    restart: unless-stopped

networks:
  screenshot_network:
    driver: bridge

volumes:
  redis_data:
  screenshot_cache:
  playwright_browsers:

secrets:
  redis_password:
    file: ./redis_password.txt 